import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col h-full w-full justify-center items-center bg-zinc-50 dark:bg-black">
        <div className="p-4 h-full grid grid-rows-[100px_auto_100px] w-full mx-auto md:w-[90%] md:px-5 lg:w-[80%] lg:px-6 xl:w-[70%] xl:px-7 bg-white dark:bg-zinc-900">
          <header className="dark:text-white">
            <Navbar />
          </header>
          <main className="dark:text-white">{children}</main>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
